/**
 * Build the iframe UI:
 *  1. esbuild bundles `src/ui/plan.tsx` (React 19 + MapLibre GL + i18n)
 *     into a single IIFE JS string.
 *  2. Reads `maplibre-gl/dist/maplibre-gl.css` and our own
 *     `src/ui/styles.css`, concatenates them.
 *  3. Emits `src/ui/dist/plan.html` with both the JS bundle and CSS
 *     inlined, plus a `<script>window.__TRANSIT_DATA__ = ___PLACEHOLDER___;</script>`
 *     line so the server can swap in real data at request time.
 *  4. Writes `src/mcp/resources/ui-html.generated.ts` exporting the
 *     template as a TS string constant, so the Worker bundle ships the
 *     HTML without filesystem access.
 *
 * The dist HTML is also written for debugging/inspection. `.gitignore`
 * excludes `src/ui/dist/`.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const ENTRY = join(ROOT, "src/ui/plan.tsx");
const STYLES = join(ROOT, "src/ui/styles.css");
const MAPLIBRE_CSS = join(
	ROOT,
	"node_modules/maplibre-gl/dist/maplibre-gl.css",
);
const DIST_DIR = join(ROOT, "src/ui/dist");
const DIST_HTML = join(DIST_DIR, "plan.html");
const GENERATED_TS = join(ROOT, "src/mcp/resources/ui-html.generated.ts");

async function bundleJs(): Promise<string> {
	const result = await build({
		entryPoints: [ENTRY],
		bundle: true,
		format: "iife",
		platform: "browser",
		target: "es2020",
		jsx: "automatic",
		minify: true,
		write: false,
		loader: { ".css": "text" },
		sourcemap: false,
		legalComments: "none",
		define: {
			"process.env.NODE_ENV": '"production"',
		},
	});
	if (!result.outputFiles || result.outputFiles.length === 0) {
		throw new Error("esbuild produced no output files");
	}
	const first = result.outputFiles[0];
	if (!first) throw new Error("esbuild output file is undefined");
	return first.text;
}

async function readCss(): Promise<string> {
	const [mapCss, ownCss] = await Promise.all([
		readFile(MAPLIBRE_CSS, "utf8"),
		readFile(STYLES, "utf8"),
	]);
	return `${mapCss}\n/* --- transit-mcp UI --- */\n${ownCss}`;
}

function htmlTemplate(jsBundle: string, css: string): string {
	// `___PLACEHOLDER___` is replaced at request time by renderUiHtml.
	return [
		"<!doctype html>",
		'<html lang="ja">',
		"<head>",
		'<meta charset="utf-8">',
		'<meta name="viewport" content="width=device-width, initial-scale=1">',
		"<title>transit-mcp</title>",
		`<style>${css}</style>`,
		"</head>",
		"<body>",
		'<div id="app"></div>',
		"<script>window.__TRANSIT_DATA__ = ___PLACEHOLDER___;</script>",
		`<script>${jsBundle}</script>`,
		"</body>",
		"</html>",
	].join("\n");
}

function escapeForBacktick(s: string): string {
	return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function generatedTs(html: string): string {
	return [
		"/**",
		" * Auto-generated by `pnpm build:ui`. Do not edit by hand.",
		" *",
		" * Contains the iframe HTML template with embedded JS + CSS.",
		" * The `___PLACEHOLDER___` token is replaced at runtime by",
		" * `renderUiHtml(...)` with the bootstrap JSON.",
		" */",
		`export const PLAN_HTML_TEMPLATE = \`${escapeForBacktick(html)}\`;`,
		"",
	].join("\n");
}

async function main(): Promise<void> {
	const start = Date.now();
	const [js, css] = await Promise.all([bundleJs(), readCss()]);
	const html = htmlTemplate(js, css);
	await mkdir(DIST_DIR, { recursive: true });
	await writeFile(DIST_HTML, html, "utf8");
	await writeFile(GENERATED_TS, generatedTs(html), "utf8");
	const ms = Date.now() - start;
	const kb = (html.length / 1024).toFixed(1);
	const jsKb = (js.length / 1024).toFixed(1);
	const cssKb = (css.length / 1024).toFixed(1);
	console.log(
		`build:ui ok in ${ms}ms — html ${kb}KB (js ${jsKb}KB, css ${cssKb}KB)`,
	);
	console.log(`  wrote ${DIST_HTML}`);
	console.log(`  wrote ${GENERATED_TS}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
